### ISSUE TITLE
malformed binary WASM file crashes "wasm-interp"

### ISSUE THREAD

**Issue by zhangbo-miuNEST** [WebAssembly/wabt#1077]
hello, 

 I'm doing AFL fuzzy of "wasm-interp" program of WABT, latest master branch.
The attached binary file can crash ""wasm-interp", probably due to empty function body.
Just decompress the zip file and run command "wasm-interp fuzzy.wasm" to reproduce it.
[fuzzy.zip](https://github.com/WebAssembly/wabt/files/3158085/fuzzy.zip)

```
ASAN:DEADLYSIGNAL
=================================================================
==13700==ERROR: AddressSanitizer: SEGV on unknown address 0x00009fff7fff (pc 0x000000570ac8 bp 0x7fffde126de0 sp 0x7fffde1268a0 T0)
==13700==The signal is caused by a READ memory access.
    #0 0x570ac7 in unsigned int wabt::interp::ReadUxAt<unsigned int>(unsigned char const*) /home/happy/wabt_afl_fuzzy_qt/wabt_afl_fuzzy/src/interp.cc:721:3
    #1 0x570ac7 in unsigned int wabt::interp::ReadUx<unsigned int>(unsigned char const**) /home/happy/wabt_afl_fuzzy_qt/wabt_afl_fuzzy/src/interp.cc:727
    #2 0x570ac7 in wabt::interp::ReadU32(unsigned char const**) /home/happy/wabt_afl_fuzzy_qt/wabt_afl_fuzzy/src/interp.cc:745
    #3 0x570ac7 in wabt::interp::ReadOpcode(unsigned char const**) /home/happy/wabt_afl_fuzzy_qt/wabt_afl_fuzzy/src/interp.cc:765
    #4 0x570ac7 in wabt::interp::Thread::Run(int) /home/happy/wabt_afl_fuzzy_qt/wabt_afl_fuzzy/src/interp.cc:1569
    #5 0x5c7dca in wabt::interp::Executor::RunDefinedFunction(unsigned int) /home/happy/wabt_afl_fuzzy_qt/wabt_afl_fuzzy/src/interp.cc:4630:24
    #6 0x5c7dca in wabt::interp::Executor::RunFunction(unsigned int, std::vector<wabt::interp::TypedValue, std::allocator<wabt::interp::TypedValue> > const&) /home/happy/wabt_afl_fuzzy_qt/wabt_afl_fuzzy/src/interp.cc:4571
    #7 0x5c8f38 in wabt::interp::Executor::RunStartFunction(wabt::interp::DefinedModule*) /home/happy/wabt_afl_fuzzy_qt/wabt_afl_fuzzy/src/interp.cc:4590:28
    #8 0x5526b5 in ReadAndRunModule(char const*) /home/happy/wabt_afl_fuzzy_qt/wabt_afl_fuzzy/src/tools/wasm-interp.cc:198:39
    #9 0x5526b5 in ProgramMain(int, char**) /home/happy/wabt_afl_fuzzy_qt/wabt_afl_fuzzy/src/tools/wasm-interp.cc:217
    #10 0x5530d5 in main /home/happy/wabt_afl_fuzzy_qt/wabt_afl_fuzzy/src/tools/wasm-interp.cc:223:10
    #11 0x7f1cde491b96 in __libc_start_main /build/glibc-OTsEL5/glibc-2.27/csu/../csu/libc-start.c:310
    #12 0x45df29 in _start (/home/happy/wabt_afl_fuzzy_qt/wabt_afl_fuzzy/build/wasm-interp+0x45df29)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV /home/happy/wabt_afl_fuzzy_qt/wabt_afl_fuzzy/src/interp.cc:721:3 in unsigned int wabt::interp::ReadUxAt<unsigned int>(unsigned char const*)
==13700==ABORTING

```

**Comment by binji** [comment]
I can't repro this issue; I tried compiling with Clang and ASAN using commit 0af114943e38a0c0a4ccb0b49b4a8fb07d1bd056. I get this error instead:

```sh
$ bin/wasm-interp fuzzy.wasm 
000003d: error: function signature count != function body count
```

**Comment by zhangbo-miuNEST** [comment]
sorry, my fault. My test is based on commit 718688b8d26f7a270054fb49f99360663fbcece7.
The latest commit 0af114943e38a0c0a4ccb0b49b4a8fb07d1bd056 is OK.

You can close this issue now.
