### ISSUE TITLE
Crash in test running when a test times out

### ISSUE THREAD

**Issue by sbc100** [WebAssembly/wabt#1243]
It looks like the test running the array of failed tests contain `Error` class as well as `TestResult`.. perhaps we should embed the `Error` in the `TestResult` on timeout to avoid this discrepancy?

```
./test/run-tests.py test/spec/memory_grow.txt  -t0.1
- test/spec/memory_grow.txt
  TIMEOUT
  STDOUT:
  
  STDERR:
  


**** FAILED ******************************************************************
Traceback (most recent call last):
  File "./test/run-tests.py", line 956, in <module>
    sys.exit(main(sys.argv[1:]))
  File "./test/run-tests.py", line 947, in main
    last_cmd = result.GetLastCommand() if result is not None else ''
AttributeError: 'Error' object has no attribute 'GetLastCommand'
```

**Comment by binji** [comment]
I believe this was fixed in #1320.
