### ISSUE TITLE
Memory corruption at wasm-decompile caused by unmatched parameters

### ISSUE THREAD

**Issue by Mem2019** [WebAssembly/wabt#1923]
Commit: `d8517aa922ddd3ffd6d7f28f00d2bb0f9853cf88`

## Reproduce

Fuzzed Sample: [decomp_heap_of.zip](https://github.com/WebAssembly/wabt/files/8748689/decomp_heap_of.zip)

Simplified Sample:

```
$ cat simplified.wat
(module
  (type (;0;) (func (param i32 i64 i64 f32) (result i32 i64 i64 f64)))
  (func (type 0) (param i32 i64 i64 f32) (result i32 i64 i64 f64)
    unreachable
    block (param i32 i64 i64 f32) (result i32 i64 i64 f64)
      unreachable
    end))
$ ./wat2wasm simplified.wat && ./wasm-decompile simplified.wasm
=================================================================
==32616==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x6080000005e0 at pc 0x5647b06e8df5 bp 0x7ffc5b2ad740 sp 0x7ffc5b2ad730
READ of size 4 at 0x6080000005e0 thread T0
    #0 0x5647b06e8df4 in wabt::Node::operator=(wabt::Node&&) (/wabt/asan/wasm-decompile+0x283df4)
    #1 0x5647b06e8dad in wabt::Node::Node(wabt::Node&&) (/wabt/asan/wasm-decompile+0x283dad)
    #2 0x5647b0729688 in std::enable_if<std::__and_<std::__not_<std::__is_tuple_like<wabt::Node> >, std::is_move_constructible<wabt::Node>, std::is_move_assignable<wabt::Node> >::value, void>::type std::swap<wabt::Node>(wabt::Node&, wabt::Node&) (/wabt/asan/wasm-decompile+0x2c4688)
    #3 0x5647b071f1ac in void std::iter_swap<__gnu_cxx::__normal_iterator<wabt::Node*, std::vector<wabt::Node, std::allocator<wabt::Node> > >, __gnu_cxx::__normal_iterator<wabt::Node*, std::vector<wabt::Node, std::allocator<wabt::Node> > > >(__gnu_cxx::__normal_iterator<wabt::Node*, std::vector<wabt::Node, std::allocator<wabt::Node> > >, __gnu_cxx::__normal_iterator<wabt::Node*, std::vector<wabt::Node, std::allocator<wabt::Node> > >) (/wabt/asan/wasm-decompile+0x2ba1ac)
    #4 0x5647b07123fc in __gnu_cxx::__normal_iterator<wabt::Node*, std::vector<wabt::Node, std::allocator<wabt::Node> > > std::_V2::__rotate<__gnu_cxx::__normal_iterator<wabt::Node*, std::vector<wabt::Node, std::allocator<wabt::Node> > > >(__gnu_cxx::__normal_iterator<wabt::Node*, std::vector<wabt::Node, std::allocator<wabt::Node> > >, __gnu_cxx::__normal_iterator<wabt::Node*, std::vector<wabt::Node, std::allocator<wabt::Node> > >, __gnu_cxx::__normal_iterator<wabt::Node*, std::vector<wabt::Node, std::allocator<wabt::Node> > >, std::random_access_iterator_tag) (/wabt/asan/wasm-decompile+0x2ad3fc)
    #5 0x5647b0703f69 in __gnu_cxx::__normal_iterator<wabt::Node*, std::vector<wabt::Node, std::allocator<wabt::Node> > > std::_V2::rotate<__gnu_cxx::__normal_iterator<wabt::Node*, std::vector<wabt::Node, std::allocator<wabt::Node> > > >(__gnu_cxx::__normal_iterator<wabt::Node*, std::vector<wabt::Node, std::allocator<wabt::Node> > >, __gnu_cxx::__normal_iterator<wabt::Node*, std::vector<wabt::Node, std::allocator<wabt::Node> > >, __gnu_cxx::__normal_iterator<wabt::Node*, std::vector<wabt::Node, std::allocator<wabt::Node> > >) (/wabt/asan/wasm-decompile+0x29ef69)
    #6 0x5647b06ea857 in wabt::AST::Construct(wabt::intrusive_list<wabt::Expr> const&, unsigned int, unsigned int, bool)::{lambda(unsigned long)#2}::operator()(unsigned long) const (/wabt/asan/wasm-decompile+0x285857)
    #7 0x5647b06eb780 in wabt::AST::Construct(wabt::intrusive_list<wabt::Expr> const&, unsigned int, unsigned int, bool) (/wabt/asan/wasm-decompile+0x286780)
    #8 0x5647b06ff25d in wabt::Decompiler::Decompile[abi:cxx11]() /wabt/src/decompiler.cc:795
    #9 0x5647b06e6685 in wabt::Decompile[abi:cxx11](wabt::Module const&, wabt::DecompileOptions const&) /wabt/src/decompiler.cc:854
    #10 0x5647b0634523 in ProgramMain(int, char**) /wabt/src/tools/wasm-decompile.cc:103
    #11 0x5647b0634881 in main /wabt/src/tools/wasm-decompile.cc:116
    #12 0x7fbc7151b0b2 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x270b2)
    #13 0x5647b06331bd in _start (/wabt/asan/wasm-decompile+0x1ce1bd)

Address 0x6080000005e0 is a wild pointer.
SUMMARY: AddressSanitizer: heap-buffer-overflow (/wabt/asan/wasm-decompile+0x283df4) in wabt::Node::operator=(wabt::Node&&)
Shadow bytes around the buggy address:
  0x0c107fff8060: fa fa fa fa 00 00 00 00 00 00 00 00 00 00 00 fa
  0x0c107fff8070: fa fa fa fa 00 00 00 00 00 00 00 00 00 00 00 fa
  0x0c107fff8080: fa fa fa fa 00 00 00 00 00 00 00 00 00 00 00 fa
  0x0c107fff8090: fa fa fa fa fd fd fd fd fd fd fd fd fd fd fd fa
  0x0c107fff80a0: fa fa fa fa 00 00 00 00 00 00 00 00 00 00 00 00
=>0x0c107fff80b0: fa fa fa fa fa fa fa fa fa fa fa fa[fa]fa fa fa
  0x0c107fff80c0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c107fff80d0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c107fff80e0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c107fff80f0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c107fff8100: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
  Shadow gap:              cc
==32616==ABORTING
Aborted
```

## Analysis

The corruption occurs at [`std::rotate`](https://github.com/WebAssembly/wabt/blob/d8517aa922ddd3ffd6d7f28f00d2bb0f9853cf88/src/decompiler-ast.h#L279), at which variable `num_vars`, which is supposed to be a positive number, is  `-3`. Therefore the first argument, `exp_stack.end() - num_vars - amount`, becomes `exp_stack.end() + 2` (`amount` is `1`), which is an invalid iterator.

### Root Cause

When [`Construct`](https://github.com/WebAssembly/wabt/blob/d8517aa922ddd3ffd6d7f28f00d2bb0f9853cf88/src/decompiler-ast.h#L236) is called on body of the `block` expression, `value_stack_depth_start` will be [assigned](https://github.com/WebAssembly/wabt/blob/d8517aa922ddd3ffd6d7f28f00d2bb0f9853cf88/src/decompiler-ast.h#L244) to `1 - 4 = -3`. The reason is that there are 4 parameters in this expression, but there is only 1 expression in `exp_stack`, so the start index will be subtracted to a negative number. Then before `Construct` returns, `value_stack_depth` is [assigned](https://github.com/WebAssembly/wabt/blob/d8517aa922ddd3ffd6d7f28f00d2bb0f9853cf88/src/decompiler-ast.h#L345) to `value_stack_depth_start`, which is `-3`. Then after `Construct` to process body of `block` is returned, `Construct` to process body of `func` continues, and it [assigns](https://github.com/WebAssembly/wabt/blob/d8517aa922ddd3ffd6d7f28f00d2bb0f9853cf88/src/decompiler-ast.h#L270) `num_vars` to `value_stack_in_variables - value_stack_depth_start`, which makes it become `-3` and causes the following crash.

### Possible Fix

However, if we change the first `unreachable` to something like `local.get 0`, the type checker will fail with message `error: type mismatch in block, expected [i32, i64, i64, f32] but got [i32]`. This suggests that the problem should be fixed at [type checker](https://github.com/WebAssembly/wabt/blob/d8517aa922ddd3ffd6d7f28f00d2bb0f9853cf88/src/type-checker.cc#L959) or [validation](https://github.com/WebAssembly/wabt/blob/d8517aa922ddd3ffd6d7f28f00d2bb0f9853cf88/src/shared-validator.cc#L1173) to consider `unreachable` expression and return an error at such situation, instead of adding anything at the AST parser.

**Comment by Mem2019** [comment]
I think this is a duplicate issue which is same as a bug reported 2 years ago, and it is still not fixed yet: https://github.com/WebAssembly/wabt/issues/1518
