### ISSUE TITLE
wasm2c/spec/simd_address.txt fails on aarch64

### ISSUE THREAD

**Issue by rathann** [WebAssembly/wabt#2240]
When running the test suite of wabt-1.0.33 on aarch64 on Fedora 38, I get this (new) test failure:
```
- test/wasm2c/spec/simd_address.txt
  expected error code 0, got 1.
  STDERR MISMATCH:
  --- expected
  +++ actual
  @@ -0,0 +1,11 @@
  +Traceback (most recent call last):
  +  File "/builddir/build/BUILD/wabt-1.0.33/test/run-spec-wasm2c.py", line 648, in <module>
  +    sys.exit(main(sys.argv[1:]))
  +             ^^^^^^^^^^^^^^^^^^
  +  File "/builddir/build/BUILD/wabt-1.0.33/test/run-spec-wasm2c.py", line 642, in main
  +    utils.Executable(main_exe, forward_stdout=True).RunWithArgs()
  +  File "/builddir/build/BUILD/wabt-1.0.33/test/utils.py", line 95, in RunWithArgs
  +    raise error
  +utils.Error: Error running "out/test/wasm2c/spec/simd_address/simd_address" (1):
  +None
  +out/test/wasm2c/spec/simd_address/simd_address-main.c:499: assertion failed: expected w2c_simd__address__1__wasm_v1280x2Eload_offset_65521(&simd__address__1__wasm_instance) to trap.
  STDOUT MISMATCH:
  --- expected
  +++ actual
  @@ -1 +1 @@
  -42/42 tests passed.
  +41/42 tests passed.
```

**Comment by sbc100** [comment]
Should we update the TODO such that it will #warning or #error when building on unsupported arch?

Also, I guess we should skip these tests on those platforms too..

**Comment by sbc100** [comment]
@rathann do you actually care about using the SIMD support in wasm2c on arm64 or are you just interested in getting the tests to pass?

**Comment by rathann** [comment]
Personally, it's the latter. We do have a growing interest in WebAssembly in Fedora, so others might actually be interested. I'll ask the other SIG members.

**Comment by rathann** [comment]
I see this on ppc64le and s390x, too.

**Comment by SoniEx2** [comment]
indeed, s390x doesn't use guard pages and falls back to range checking, while this issue only occurs with guard pages. #2545 would fix it everywhere.
