### ISSUE TITLE
WASM code on demo page uses WASM_BINARY_VERSION `0d00 0000` instead of `0100 0000`

### ISSUE THREAD

**Issue by hi7** [WebAssembly/wabt#369]
The code on the right side of the demo page displays `0d00 0000` at position `0000004`. This should be `0100 0000` right?
In the [online demo](https://cdn.rawgit.com/WebAssembly/wabt/e528a622caa77702209bf0c3654ca78456c41a52/demo/index.html) it seems to work but in my local build (simple `make` on Debian) I got an exception: 

> index.html:1 Uncaught (in promise) abort() at Error
    at jsStackTrace (http://localhost:63342/WABT/demo/libwabt.js:1:41985)
    at stackTrace (http://localhost:63342/WABT/demo/libwabt.js:1:42156)
    at Object.abort (http://localhost:63342/WABT/demo/libwabt.js:19:28569)
    at _abort (http://localhost:63342/WABT/demo/libwabt.js:1:48991)
    at Object.co [as _free] (http://localhost:63342/WABT/demo/libwabt.js:11:37793)
    at free (http://localhost:63342/WABT/demo/libwabt.js:1:1538)
    at Value.Module.onRuntimeInitialized.Value.$free (http://localhost:63342/WABT/demo/libwabt.js:1:11365)
    at AstLexer.Module.onRuntimeInitialized.AstLexer.$destroy (http://localhost:63342/WABT/demo/libwabt.js:1:20597)
    at Script.Module.onRuntimeInitialized.Script.$destroy (http://localhost:63342/WABT/demo/libwabt.js:1:23136)
    at http://localhost:63342/WABT/demo/demo.js:116:26

**Comment by binji** [comment]
Yeah, the JavaScript demo has been out-of-date for a while now, and I haven't gotten the chance to update it. It's pretty bad to have it displaying output with the wrong version, though.

**Comment by binji** [comment]
This is fixed in https://github.com/WebAssembly/wabt/commit/5a0feb1d21a9448b53ad31440af666f13705858d.
