### ISSUE TITLE
MSan reported use of uninitialized value

### ISSUE THREAD

**Issue by HongxuChen** [WebAssembly/wabt#850]
When I build wabt with `make clang-release-msan`, and run `wasm2wat` against almost any other files (e.g., `./wasm2wat ./CMakeCache.txt`), MSan reports use of uninitialized value such as:

```
Uninitialized bytes in __interceptor_strlen at offset 16 inside [0x702000000380, 17)
==23518==WARNING: MemorySanitizer: use-of-uninitialized-value
    #0 0x4c5425 in std::char_traits<char>::length(char const*) /usr/bin/../lib/gcc/x86_64-linux-gnu/8.0.1/../../../../include/c++/8.0.1/bits/char_traits.h:320:9
    #1 0x4c5425 in wabt::string_view::string_view(char const*) /home/hongxu/tests/wabt/src/string-view.h:196
    #2 0x4c5425 in ProgramMain(int, char**) /home/hongxu/tests/wabt/src/tools/wasm2wat.cc:108
    #3 0x4c5e43 in main /home/hongxu/tests/wabt/src/tools/wasm2wat.cc:148:10
    #4 0x7f7044e5bb96 in __libc_start_main /build/glibc-OTsEL5/glibc-2.27/csu/../csu/libc-start.c:310
    #5 0x4489c9 in _start (/home/hongxu/tests/wabt/out/clang/Release/msan/wasm2wat+0x4489c9)
SUMMARY: MemorySanitizer: use-of-uninitialized-value /usr/bin/../lib/gcc/x86_64-linux-gnu/8.0.1/../../../../include/c++/8.0.1/bits/char_traits.h:320:9 in std::char_traits<char>::length(char const*)
Exiting
```

```
$ clang --version
clang version 6.0.1-svn332782-1~exp1~20180520222702.86 (branches/release_60)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
```

Any hints what's happening?

**Comment by binji** [comment]
I believe it is because memory sanitizer requires all libraries to be instrumented as well, see the documentation [here](https://clang.llvm.org/docs/MemorySanitizer.html#handling-external-code). I think it worked originally because wabt was written in C and the msan runtime library includes interceptors for common functions. Since switching to C++, we'd need to build the C++ standard library with msan enabled too.

**Comment by HongxuChen** [comment]
Okay, got it.
